---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ocsinventory.fullname" . }}-config
  labels:
    {{- include "ocsinventory.labels" . | nindent 4 }}
data:
  ocsinventory.ini: |
    {{ .Values.phpconfig.ocsinventory | nindent 4 }}
...
{{- if .Values.proxy.enabled }}
---
apiVersion: v1
data:
  ocsapi.htpasswd: |
    {{ htpasswd .Values.proxy.auth.username .Values.proxy.auth.password | nindent 4 }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-auth
...
---
apiVersion: v1
data:
  nginx.conf.template: |
    {{ .Values.proxy.nginxConfig | nindent 4}}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxyconf
{{- end }}