{{- if .Values.proxy.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Release.Name }}-proxy
  name: {{ .Release.Name }}-proxy
spec:
  host: {{ .Values.proxy.hostname }}
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ .Release.Name }}-proxy
    weight: 100
  wildcardPolicy: None
{{- end }}